### ISSUE TITLE
20.05 Zadanie dla zespołu (możliwy konflikt)

### ISSUE THREAD

**Issue by meho55555** [PiotrPiotrPiotr/repozytorium-baza#41]
Importowanie bazy do magazynu,
Jest to trudna funkcja więc 3 osoby muszą się za nią zabrać.

**Comment by sebix22** [comment]
Ktoś mógłby przybliżyć działanie tej funkcji bo nie bardzo wiem co mamy zrobić.

**Comment by PiotrPiotrPiotr** [comment]
Tutaj miałem na myśli, że z pliku tekstowego można byłoby odczytać dane gry i wrzucić je do listy...
