### ISSUE TITLE
Organizacja plików

### ISSUE THREAD

**Issue by dominik1111** [PiotrPiotrPiotr/repozytorium-baza#9]
Jak organizujemy repozytorium ? Co myślicie o klasycznym podziale na trzy pliki : header, implementacja, main ?

**Comment by PiotrPiotrPiotr** [comment]
Oki, po przemyśleniu myślę, że tak będzie najwygodniej ;)

**Comment by sebix22** [comment]
No tak będzie najlepiej bo tak samo jak jesteś przyzwyczajeni do pracy na informatyce.

**Comment by meho55555** [comment]
Dane wczytywane z kodu czy z pliku np. "dane.txt"?

**Comment by dominik1111** [comment]
Z kodu, mniej roboty :)

**Comment by sebix22** [comment]
Teraz tak sobie myślę i może lepiej będzie jak nazwiemy te pliki gry.h, gry.c i main.c? :dancer:

**Comment by PiotrPiotrPiotr** [comment]
Zmieniłem nazwy, co ułatwi pracę...

Dopiero teraz przeczytałem, że Sebastian napisał "gry", a ja nazwałem "baza", trudno najwyżej możesz zmienić ;)
